### ISSUE TITLE
Not seeing mix tasks 

### ISSUE THREAD

**Issue by vivdiwakar** [ahamez/protox#26] opened 2020-11-18 09:48 UTC
Hi @ahamez 

First off, great work on this, I am interested in learning more about Protobufs with Elixir and possibly using this is production. I am using Protox 1.2, and after running `mix deps.get` I don't have the mix task `mix protox.generate` to generate the modules. Can you please point me at what I am missing or doing wrong?

```$ elixir -v
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```

Thanks in advance,

Viv

**Comment by ahamez** [comment] 2020-11-18 10:09
Hello @vivdiwakar and thanks for the report!

I wasn't able to reproduce your issue: I created a new Elixir project (`mix new foo`), then I added the protox dependency (`{:protox, "~> 1.2"}` in mix.exs `deps()`), followed by `mix deps.get`. I then ran ` mix protox.generate --output-path=./lib/message.ex path/to/file.proto`. As expected, the file `message.ex` is generated in the correct location.

Can you give me the exact steps to reproduce the error, as well as the error message, if any?

**Comment by vivdiwakar** [comment] 2020-11-18 16:35
Hi Alexandre,

Okay, thanks for checking and your very prompt response. I'll try again in
a pristine project and get back to you.

The only difference in the steps is I am running an umbrella project, and
added the protox dependency in the app project, rather than the top-level
project. Unfortunately I won't be able to confirm exact steps or try this
again till I am off work and back on my personal laptop.

I'll let you know.

Thanks,

Viv

**Comment by vivdiwakar** [comment] 2020-11-18 21:42
Hi @ahamez,

So I can confirm that the steps you outline work, even within an umbrella project. What threw me off was that `mix help` does not show any tasks for `protox.*` so I (mistakenly) assumed they were not present. My apologies for this.

Out of interest, can you please tell me why no protox tasks are listed in `mix help`, if they are nevertheless present?

Thanks.

**Comment by ahamez** [comment] 2020-11-18 21:57
Because I didn't know it was [possible](https://hexdocs.pm/mix/Mix.Task.html#module-attributes) 😅. But thanks to you, it's now fixed!

**Closed as completed** 2020-11-18 21:56 UTC
Labels: enhancement

**Comment by vivdiwakar** [comment] 2020-11-18 22:06
Oh brilliant! Thanks for the prompt turnaround in fixing this.

**Comment by vivdiwakar** [comment] 2020-11-18 22:08
Forgot to mention, I got 1.2.2 version and I see everything - thanks again.
